<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Carreras</title>
    <link rel="stylesheet" href="css/bootstrap.css">
</head>

<body>
    <!--Barra de Navegación-->
    <?php include('nav.html') ?>}

    <!--Esta Administración-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/boss (1).svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Administración</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseExample" class="btn btn-light" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="collapseExample">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseExample">

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#ITP">
                        <img src="Iconos/0.5x/Recurso 2@0.5x.png" alt="ITParral">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Instituo Tecnológico de Parral</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.itparral.edu.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#UACH">
                        <img src="Iconos/0.5x/Recurso 1@0.5x.png" alt="UACH">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Universidad Autonoma de Chihuahua</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.uach.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#CCU">
                        <img src="Iconos/0.5x/CCU@0.5x.png" alt="UACH">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Centro Cultural Universitario</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.ccu.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!--Esta eAdministracion de Empresas turisticas-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/adminConst.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Administración de Empresas Turísticas</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseAET" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseAET">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseAET">

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#URN">
                        <img src="Iconos/0.5x/URN@0.5x.png" alt="URN">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Universidad Regional del Norte</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.urn.edu.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!--Esta Admon Financiera-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/accounting.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Administración Financiera</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseAF" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseAF">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseAF">


                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#UACH">
                        <img src="Iconos/0.5x/Recurso 1@0.5x.png" alt="UACH">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Universidad Autonoma de Chihuahua</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.uach.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>


            </div>
        </div>
    </div>

    <!--Esta ADMINISTRACIÓN Y gESTIÓN Pública-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/politics.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Administración de Gestion Pública</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseAGP" class="btn btn-light" data-toggle="collapse" role="button" 
            aria-expanded="false" aria-controls="collapseAGP">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseAGP">

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#UACH">
                        <img src="Iconos/0.5x/Recurso 1@0.5x.png" alt="UACH">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Universidad Autonoma de Chihuahua</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.uach.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!--Esta es Admon y gestion pùblica-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/gestPub.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Administración y Gestión Pública</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseAYGP" class="btn btn-light" data-toggle="collapse" role="button"
             aria-expanded="false" aria-controls="collapseAYGP">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseAYGP">

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#UACH">
                        <img src="Iconos/0.5x/Recurso 1@0.5x.png" alt="UACH">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Universidad Autonoma de Chihuahua</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.uach.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--Esta Arquitectura-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/blueprint.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Arquitectura</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseARQUI" class="btn btn-light" data-toggle="collapse"
             role="button" aria-expanded="false" aria-controls="collapseARQUI">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseARQUI">
                <?php include('linkITP.html') ?>
            </div>
        </div>
    </div>

    <!--Esta es Artes-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/artes.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Artes Plasticas</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseArtes" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseArtes">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseArtes">
                <?php include('linkUACH.html') ?>
            </div>
        </div>
    </div>

    <!--Esta es Ciencias Forences-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/forense.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Ciencias Forenses</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseCienciasF" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseCienciasF">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseCienciasF">

                <?php include('linkCCU.html') ?>

            </div>
        </div>
    </div>

    <!--Esta es Ciencias Políticas-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/politica.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Ciencias Políticas</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseCienciasP" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseCienciasP">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseCienciasP">
                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#URN">
                        <img src="Iconos/0.5x/IISCH@0.5x.png" alt="URN">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0"></h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.iisch.com" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--Esta es Ciencias de la Comunicación-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/comunicaciones.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Ciencias de la Comunicación</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseCienciasC" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseCienciasC">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseCienciasC">
                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#URN">
                        <img src="Iconos/0.5x/URN@0.5x.png" alt="URN">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Universidad Regional del Norte</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.urn.edu.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--Esta es Comunicación y Periodismo-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/periodismo.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Comunicación y Periodismo</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseComunYP" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseComunYP">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseComunYP">

                <?php include('linkCCU.html') ?>

            </div>
        </div>
    </div>

    <!--Esta es Contador Público-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/contabilidad.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Contabilidad Pública</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseContPub" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseContPub">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseContPub">

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#ITP">
                        <img src="Iconos/0.5x/Recurso 2@0.5x.png" alt="ITParral">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Instituo Tecnológico de Parral</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.itparral.edu.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#UACH">
                        <img src="Iconos/0.5x/Recurso 1@0.5x.png" alt="UACH">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Universidad Autonoma de Chihuahua</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.uach.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!--Esta es Criminología-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/Criminologia.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Criminología</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseCrimino" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseCrimino">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseCrimino">
                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#UNES">
                        <img src="Iconos/0.5x/UNES@0.5x.png" alt="UNES">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Universidad España de Durango</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.unes.edu.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--Esta es Derecho-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/derecho.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Derecho</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseDerecho" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseDerecho">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseDerecho">
                <?php include('linkUACH.html') ?>

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#URN">
                        <img src="Iconos/0.5x/URN@0.5x.png" alt="URN">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Universidad Regional del Norte</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.urn.edu.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>
                <?php include('linkCCU.html') ?>
            </div>
        </div>
    </div>

    <!--Esta es derecho bUROCRÁTICO-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/burocratico.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Derecho Burocrático</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseDBuro" class="btn btn-light" data-toggle="collapse" role="button" 
            aria-expanded="false" aria-controls="collapseDBuro">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseDBuro">

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#INESAP">
                        <img src="Iconos/0.5x/INESAP@0.5x.png" alt="UNES">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">INESAP</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.inesap.edu.mx/" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!--Esta es dISEÑO GRAFICO-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/diseñador.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Diseño Gráfico</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseDiseG" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseDiseG">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseDiseG">

                <?php include('linkCCU.html') ?>

            </div>
        </div>
    </div>

    <!--Esta es eCONOMÍA-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/economy.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Economía</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseEconomia" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseEconomia">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseEconomia">

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#UACH">
                        <img src="Iconos/0.5x/Recurso 1@0.5x.png" alt="UACH">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Universidad Autonoma de Chihuahua</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.uach.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!--Esta es Edificacion y admin obras-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/architect.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Edificación y Administración de Obra</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseEYAO" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseEYAO">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseEYAO">
                <?php include('linkCCU.html') ?>
            </div>
        </div>
    </div>

    <!--Esta es Educación Preescolar-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/preescolar.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Educación Preescolar</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapsePreescolar" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapsePreescolar">
                Ver Universidades
            </a>
            <div class="collapse" id="collapsePreescolar">
                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#NE">
                        <img src="Iconos/0.5x/NormalE@0.5x.png" alt="Normal Experimental">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0"></h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="https://escuela-normal-experimental-miguel-hidalgo.webnode.es/" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--Esta es Educación primaria-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/primaria.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Educación Primaria</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapsePrimaria" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapsePrimaria">
                Ver Universidades
            </a>
            <div class="collapse" id="collapsePrimaria">
                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#NE">
                        <img src="Iconos/0.5x/NormalE@0.5x.png" alt="Normal Experimental">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0"></h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="https://escuela-normal-experimental-miguel-hidalgo.webnode.es/" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--Esta es Enfermería-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/nurse.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Enfermería</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseEnfermeria" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseEnfermeria">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseEnfermeria">
                <?php include('linkUACH.html') ?>
            </div>
        </div>
    </div>

    <!--Esta es Enseñanza y APRENDIJASEE-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/aprendisaje.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Enseñanza y Aprendisaje</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseEnseYA" class="btn btn-light" data-toggle="collapse"
             role="button" aria-expanded="false" aria-controls="collapseEnseYA">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseEnseYA">

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#NS">
                        <img src="Iconos/0.5x/NormalSuperior@0.5x.png" alt="UNES">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Normal Superior</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.ensech.edu.mx/unidad-parral.html" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!--Esta es Gestion ded negocios y proyectos-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/gestionProyectos.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Gestión de Negocios y Proyectos</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseGNYP" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseGNYP">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseGNYP">

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#UTP">
                        <img src="Iconos/0.5x/UTP@0.5x.png" alt="UACH">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Universidad Tecnológica de Parral</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.utparral.edu.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!--Esta es Ing Civil-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/civil.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Ingeniería Civil</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseCivil" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseCivil">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseCivil">
                <?php include('linkUACH.html') ?>
            </div>
        </div>
    </div>

    <!--Esta es ING en Electro-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/electro.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Ingeniería Electromecánica</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseElectro" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseElectro">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseElectro">
                <?php include('linkITP.html') ?>
            </div>
        </div>
    </div>

    <!--Esta es Ing en Gestion Empresarial-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/boss.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Ingeniería en Gestión Empresarial</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseGestionE" class="btn btn-light" data-toggle="collapse" role="button" 
            aria-expanded="false" aria-controls="collapseGestionE">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseGestionE">

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#ITP">
                        <img src="Iconos/0.5x/Recurso 2@0.5x.png" alt="ITParral">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Instituo Tecnológico de Parral</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.itparral.edu.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#CCU">
                        <img src="Iconos/0.5x/CCU@0.5x.png" alt="UACH">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Centro Cultural Universitario</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.ccu.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!--Esta es Ing en lOGÍSTICA-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/logistica.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Ingeniería en Lógistica</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseLogi" class="btn btn-light" data-toggle="collapse"
            role="button" aria-expanded="false" aria-controls="collapseLogi">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseLogi">

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#CCU">
                        <img src="Iconos/0.5x/CCU@0.5x.png" alt="UACH">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Centro Cultural Universitario</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.ccu.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!--Esta es ING EN MANTENIMIENTO INDUSTRIAL-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/monitoring.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Ingeniería en Mantenimiento Industrial</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapsManIndu" class="btn btn-light" data-toggle="collapse"
             role="button" aria-expanded="false" aria-controls="collapseManIndu">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseManIndu">
                <?php include('linkUTP.html') ?>
            </div>
        </div>
    </div>
    </div>

    <!--Esta es iNG EN MINERIA-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/miner.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Ingeniería en Mínas</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseMina" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseMina">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseMina">
                <?php include('linkITP.html') ?>
                <br>
                <?php include('linkUTP.html') ?>
            </div>
        </div>
    </div>
    </div>

    <!--Esta es  ING EN SISTEMAS COMPUTACIONALESS-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/sistemas.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Ingeniería en Sistemas Computacionales</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseSisCom" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseSisCom">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseSisCom">

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#ITP">
                        <img src="Iconos/0.5x/Recurso 2@0.5x.png" alt="ITParral">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Instituo Tecnológico de Parral</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.itparral.edu.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!--Esta es ING EN SISTEMAS PRODUCUTIVOS-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/adminConst.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Ingeniería en Sistemas Productivos</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseSisPro" class="btn btn-light" data-toggle="collapse"
             role="button" aria-expanded="false" aria-controls="collapseSisPro">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseSisPro">

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#UTP">
                        <img src="Iconos/0.5x/UTP@0.5x.png" alt="UACH">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Universidad Tecnológica de Parral</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.utparral.edu.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <!--Esta es ING EN TICS-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/TICS.svg" alt="tics" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Tecnológias de la Información</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseTICS" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseTICS">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseTICS">

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#UTP">
                        <img src="Iconos/0.5x/UTP@0.5x.png" alt="UACH">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Universidad Tecnológica de Parral</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.utparral.edu.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#CCU">
                        <img src="Iconos/0.5x/CCU@0.5x.png" alt="UACH">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Centro Cultural Universitario</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.ccu.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--Esta es ING IINDUSTRIAL-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/industrial.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Ingeniería Industrial</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseIndus" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseIndus">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseIndus">

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#ITP">
                        <img src="Iconos/0.5x/Recurso 2@0.5x.png" alt="ITParral">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Instituo Tecnológico de Parral</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.itparral.edu.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!--Esta es ING EN MECATRONICA-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/Mecatronica.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Mecatrónica</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseMecatronic" class="btn btn-light" data-toggle="collapse" role="button" 
            aria-expanded="false" aria-controls="collapseMecatronic">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseMecatronic">
                <?php include('linkITP.html') ?>
            </div>
        </div>
    </div>

    <!--Esta es ING QUIMICA-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/chemistry.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Ingeniería Química</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseQuimica" class="btn btn-light" data-toggle="collapse"
            role="button" aria-expanded="false" aria-controls="collapseQuimica">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseQuimica">
                <?php include('linkITP.html') ?>
            </div>
        </div>
    </div>

    <!--Esta es INTERVENCION EDUCATIVA-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/intervencion.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en intervención Educativa</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseIE" class="btn btn-light" data-toggle="collapse" role="button" 
            aria-expanded="false" aria-controls="collapseIE">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseIE">
                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#UPN">
                        <img src="Iconos/0.5x/UPN@0.5x.png" alt="UPN">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">UPN</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.UPENECH.edu.mx/" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--Esta es MEDICINA-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/doctor.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Medicina</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseMedicina" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseMedicina">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseMedicina">
                <?php include('linkUACH.html') ?>
            </div>
        </div>
    </div>

    <!--Esta es nEGOCIOS INTErnacionales-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/international.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Negocios Internacionales</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseNI" class="btn btn-light" data-toggle="collapse" role="button" 
            aria-expanded="false" aria-controls="collapseMI">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseNI">

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#UACH">
                        <img src="Iconos/0.5x/Recurso 1@0.5x.png" alt="UACH">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Universidad Autonoma de Chihuahua</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.uach.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!--Esta es Negocios y mercadotecnia-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/negg.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Gestión de Negocios y Mercadotecnia</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseNYM" class="btn btn-light" data-toggle="collapse" role="button" 
            aria-expanded="false" aria-controls="collapseNYM">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseNYM">

                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#CCU">
                        <img src="Iconos/0.5x/CCU@0.5x.png" alt="UACH">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Centro Cultural Universitario</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.ccu.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!--Esta es Nutrici[ona-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/diet.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Nutrición</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseNutri" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapseNutri">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseNutri">
                <?php include('linkUACH.html') ?>
                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#UNES">
                        <img src="Iconos/0.5x/UNES@0.5x.png" alt="UNES">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">Universidad España de Durango</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.uach.mx" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--Esta es pedagogia-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/pedagogia.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Pedagogía</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapsePedago" class="btn btn-light" data-toggle="collapse" 
            role="button" aria-expanded="false" aria-controls="collapsePedago">
                Ver Universidades
            </a>
            <div class="collapse" id="collapsePedago">
                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#UPN">
                        <img src="Iconos/0.5x/UPN@0.5x.png" alt="UPN">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">UPN</h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.UPENECH.edu.mx/" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>
                <?php include('linkCCU.html') ?>
            </div>
        </div>
    </div>

    <!--Esta es Psicologia-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/psychology.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Psicología</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapsePsi" class="btn btn-light" data-toggle="collapse" role="button" 
            aria-expanded="false" aria-controls="collapsePsi">
                Ver Universidades
            </a>
            <div class="collapse" id="collapsePsi">
                <div class="media mt-3">
                    <a class="pr-3" href="universidades.php#URN">
                        <img src="Iconos/0.5x/IISCH@0.5x.png" alt="URN">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0"></h5>
                        <!--Hablar sobre el Tec y esta área-->
                        <a href="http://www.iisch.com" class="btn btn-dark" role="button">Ver Pagina</a>
                    </div>
                </div>

                <?php include('linkCCU.html') ?>
            </div>
        </div>
    </div>

    <!--Esta es Trabajjo social-->
    <div class="media">
        <img class="mr-3" src="carreras/iconos/social.svg" alt="admin" style="width:8%;">
        <div class="media-body">
            <h5 class="mt-0">Licenciatura en Trabajo Social</h5>
            <!--Insertar texto de la licenciatura-->
            <a href="#collapseTS" class="btn btn-light" data-toggle="collapse" role="button" 
            aria-expanded="false" aria-controls="collapseTS">
                Ver Universidades
            </a>
            <div class="collapse" id="collapseTS">
                <?php include('link.CCU.html') ?>
            </div>
        </div>
    </div>

    <?php include('footer.html')?>
    <script src="js/jquerty.js"></script>
    <script src="js/bootstrap.min.js"></script>
</body>

</html>