CREATE TABLE UACH(
  id_L INT PRIMARY KEY NOT NULL,
  nombre TEXT NOT NULL
);
CREATE TABLE ITP(
  id_L INT PRIMARY KEY NOT NULL,
  nombre TEXT NOT NULL
);
CREATE TABLE UTP(
  id_L INT PRIMARY KEY NOT NULL,
  nombre TEXT NOT NULL
);
CREATE TABLE IISCH(
  id_L INT PRIMARY KEY NOT NULL,
  nombre TEXT NOT NULL
);
CREATE TABLE CCU(
  id_L INT PRIMARY KEY NOT NULL,
  nombre TEXT NOT NULL
);
CREATE TABLE INESAP(
  id_L INT PRIMARY KEY NOT NULL,
  nombre TEXT NOT NULL
);
CREATE TABLE UNES(
  id_L INT PRIMARY KEY NOT NULL,
  nombre TEXT NOT NULL
);
CREATE TABLE UPN(
  id_L INT PRIMARY KEY NOT NULL,
  nombre TEXT NOT NULL
);
CREATE TABLE NormalExperimentalMiguielHidalgo(
  id_L INT PRIMARY KEY NOT NULL,
  nombre TEXT NOT NULL
);
CREATE TABLE NormalSuperiorJoseMedrano(
  id_L INT PRIMARY KEY NOT NULL,
  nombre TEXT NOT NULL
);
